[phases.install]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "pip install --no-cache-dir -r backend/requirements.txt"
]

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONPATH = "."

[start]
# Use the explicit backend app module path
[phases.setup]
# Ensure Python and pip are available in the image
nixPkgs = ["python311", "python311Packages.pip", "bash"]
command = "uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
