[phases.setup]
# Ensure Python and pip are available in the image
nixPkgs = ["python311", "python311Packages.pip", "bash"]

[phases.install]
cmds = [
  "pip install --no-cache-dir --upgrade setuptools wheel",
  "pip install --no-cache-dir -r backend/requirements.txt"
]

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONPATH = "."

[start]
cmd = "uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
